name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - name: Login to Docker Registry
      run: docker login -u ymtkudasai -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Compose
      run: docker compose build
      
    - name: Push
      run: docker compose push
    
